version: "3"

services:
    octordle:
        image: ghcr.io/boriselec/octordle-ru:ru
        container_name: octordle
        logging:
            driver: local
    rimworld-art:
        image: ghcr.io/boriselec/rimworld_artaiserver:main
        container_name: rimworld-art
        logging:
            driver: local
            options:
                max-file: "20"
        volumes:
            - "./www/rimworld-art/images:/mnt/images"
            - "./secret:/mnt/secret"
        environment:
            - GCP_PROJECT=${RIMWORLD_ART_GCP_PROJECT}
            - GCP_ZONE=${RIMWORLD_ART_GCP_ZONE}
            - GCP_INSTANCE=${RIMWORLD_ART_GCP_INSTANCE}
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus/:/etc/prometheus/
            - ./prometheus_data:/prometheus
    proxy:
        image: linuxserver/letsencrypt
        container_name: proxy
        logging:
            driver: local
        depends_on:
            - "octordle"
            - "rimworld-art"
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./site-confs:/config/nginx/site-confs
            - ./www:/config/www
        environment:
            - EMAIL=boris-elec@mail.ru
            - URL=boriselec.com
            - VALIDATION=http