version: "3"

services:
    octordle:
        image: ghcr.io/boriselec/octordle-ru:ru
        container_name: octordle
        logging:
            driver: local
    rimworld-art:
        image: ghcr.io/boriselec/rimworld_artaiserver:main
        container_name: rim
        logging:
            driver: local
            options:
                max-file: "20"
        volumes:
            - "./www/rimworld-art/images:/mnt/images"
            - "./secret:/mnt/secret"
        environment:
            - GCP_PROJECT=${RIMWORLD_ART_GCP_PROJECT}
            - GCP_ZONE=${RIMWORLD_ART_GCP_ZONE}
            - GCP_INSTANCE=${RIMWORLD_ART_GCP_INSTANCE}
            - GCP_IDLE_STOPAFTERSECONDS=${RIMWORLD_ART_GCP_IDLE_STOPAFTERSECONDS}
            - QUEUE_SIZE_MAX=${RIMWORLD_ART_QUEUE_SIZE_MAX}
            - LIMIT_USER=${RIMWORLD_ART_LIMIT_USER}
            - PRIORITY_USERID_LIST=${RIMWORLD_ART_PRIORITY_USERID_LIST}
            - IMAGE_FOLDER_LIMIT=${RIMWORLD_ART_IMAGE_FOLDER_LIMIT}
            - GENERATOR_URL=false
    prometheus:
        image: prom/prometheus
        user: "0:0"
        container_name: prometheus
        volumes:
            - ./prometheus/:/etc/prometheus/
            - ./prometheus_data:/prometheus
        logging:
            driver: local
        restart: on-failure
    grafana:
        image: grafana/grafana-oss
        container_name: grafana
        volumes:
            - ./grafana/datasources:/etc/grafana/provisioning/datasources/
            - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
        environment:
            - GF_SERVER_ROOT_URL=https://boriselec.com/grafana
            - GF_SERVER_SERVE_FROM_SUB_PATH=true
            - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
            - GF_SMTP_ENABLED=true
            - GF_SMTP_HOST=smtp.gmail.com:587
            - GF_SMTP_USER=${GRAFANA_GMAIL_MAIL}
            - GF_SMTP_FROM_ADDRESS=${GRAFANA_GMAIL_MAIL}
            - GF_SMTP_FROM_NAME=Alert
            - GF_SMTP_PASSWORD=${GRAFANA_GMAIL_PASS}
            - GF_SMTP_SKIP_VERIFY=true
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
        logging:
            driver: local
    proxy:
        image: linuxserver/letsencrypt
        container_name: proxy
        logging:
            driver: local
        depends_on:
            - "octordle"
            - "rimworld-art"
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./site-confs:/config/nginx/site-confs
            - ./www:/config/www
        environment:
            - EMAIL=boris-elec@mail.ru
            - URL=boriselec.com
            - VALIDATION=http